comment on type public.git_provider is '代码托管平台枚举 / Git provider enum';
comment on type public.member_role is '组织成员角色枚举 / Membership role enum';
comment on type public.repo_status is '仓库状态枚举 / Repository status enum';
comment on type public.review_mode is '审查模式枚举 / Review mode enum';
comment on type public.output_language is '输出语言枚举 / Output language enum';
comment on type public.review_run_status is '审查运行状态枚举 / Review run status enum';
comment on type public.review_trigger is '审查触发来源枚举 / Review trigger enum';
comment on type public.issue_type is '问题类型枚举 / Issue type enum';
comment on type public.severity is '严重级别枚举 / Severity enum';
comment on type public.issue_status is '问题状态枚举 / Issue status enum';
comment on type public.comment_status is '评论状态枚举 / Comment status enum';
comment on type public.feedback_type is '反馈类型枚举 / Feedback type enum';
comment on type public.ai_provider is '模型提供商枚举 / AI provider enum';
comment on type public.ai_task_type is 'AI 任务类型枚举 / AI task type enum';
comment on type public.rule_source_type is '规则来源类型枚举 / Rule source type enum';

comment on table public.app_users is '平台用户主体表 / Application users';
comment on column public.app_users.id is '主键 ID / Primary key ID';
comment on column public.app_users.external_subject is '外部认证主体标识 / External auth subject';
comment on column public.app_users.email is '用户邮箱 / User email';
comment on column public.app_users.display_name is '展示名称 / Display name';
comment on column public.app_users.avatar_url is '头像地址 / Avatar URL';
comment on column public.app_users.metadata is '扩展资料 JSON / Extended metadata JSON';
comment on column public.app_users.created_at is '创建时间 / Created at';
comment on column public.app_users.updated_at is '更新时间 / Updated at';

comment on table public.organizations is '组织表 / Organizations';
comment on column public.organizations.id is '主键 ID / Primary key ID';
comment on column public.organizations.name is '组织名称 / Organization name';
comment on column public.organizations.slug is '组织唯一标识 / Organization unique slug';
comment on column public.organizations.status is '组织状态 / Organization status';
comment on column public.organizations.plan_tier is '套餐层级 / Subscription plan tier';
comment on column public.organizations.default_output_language is '默认输出语言 / Default output language';
comment on column public.organizations.default_review_mode is '默认审查模式 / Default review mode';
comment on column public.organizations.owner_user_id is '组织拥有者用户 ID，对应 app_users.id / Owner user ID referencing app_users.id';
comment on column public.organizations.created_at is '创建时间 / Created at';
comment on column public.organizations.updated_at is '更新时间 / Updated at';

comment on table public.memberships is '组织成员关系表 / Organization memberships';
comment on column public.memberships.id is '主键 ID / Primary key ID';
comment on column public.memberships.organization_id is '组织 ID / Organization ID';
comment on column public.memberships.user_id is '用户 ID，对应 app_users.id / User ID referencing app_users.id';
comment on column public.memberships.role is '成员角色 / Membership role';
comment on column public.memberships.status is '成员状态 / Membership status';
comment on column public.memberships.invited_by is '邀请人用户 ID，对应 app_users.id / Invited by user ID referencing app_users.id';
comment on column public.memberships.joined_at is '加入时间 / Joined at';
comment on column public.memberships.created_at is '创建时间 / Created at';
comment on column public.memberships.updated_at is '更新时间 / Updated at';

comment on table public.repositories is '仓库主表 / Repositories';
comment on column public.repositories.id is '主键 ID / Primary key ID';
comment on column public.repositories.organization_id is '所属组织 ID / Organization ID';
comment on column public.repositories.provider is '代码托管平台 / Git provider';
comment on column public.repositories.provider_repo_id is '平台侧仓库 ID / Provider repository ID';
comment on column public.repositories.name is '仓库名称 / Repository name';
comment on column public.repositories.full_name is '仓库全名，例如 owner/repo / Full repository name, e.g. owner/repo';
comment on column public.repositories.default_branch is '默认分支 / Default branch';
comment on column public.repositories.status is '仓库状态 / Repository status';
comment on column public.repositories.default_output_language is '仓库默认输出语言 / Repository default output language';
comment on column public.repositories.default_review_mode is '仓库默认审查模式 / Repository default review mode';
comment on column public.repositories.default_ai_binding_id is '默认模型绑定 ID / Default AI binding ID';
comment on column public.repositories.last_synced_at is '最后同步时间 / Last synced at';
comment on column public.repositories.created_at is '创建时间 / Created at';
comment on column public.repositories.updated_at is '更新时间 / Updated at';

comment on table public.repo_integrations is '仓库接入配置表 / Repository integrations';
comment on column public.repo_integrations.id is '主键 ID / Primary key ID';
comment on column public.repo_integrations.organization_id is '所属组织 ID / Organization ID';
comment on column public.repo_integrations.repository_id is '仓库 ID / Repository ID';
comment on column public.repo_integrations.provider is '代码托管平台 / Git provider';
comment on column public.repo_integrations.installation_id is '平台安装 ID 或应用安装标识 / Provider installation ID';
comment on column public.repo_integrations.provider_owner_id is '平台侧 owner ID / Provider owner ID';
comment on column public.repo_integrations.credential_vault_secret_id is '访问凭证的 Vault Secret ID / Vault secret ID for provider credentials';
comment on column public.repo_integrations.webhook_secret_vault_secret_id is 'Webhook 密钥的 Vault Secret ID / Vault secret ID for webhook secret';
comment on column public.repo_integrations.status is '接入状态 / Integration status';
comment on column public.repo_integrations.metadata is '接入扩展信息 JSON / Integration metadata JSON';
comment on column public.repo_integrations.created_at is '创建时间 / Created at';
comment on column public.repo_integrations.updated_at is '更新时间 / Updated at';

comment on table public.webhook_events is 'Webhook 事件流水表 / Webhook event ledger';
comment on column public.webhook_events.id is '主键 ID / Primary key ID';
comment on column public.webhook_events.organization_id is '所属组织 ID，可为空 / Organization ID, nullable';
comment on column public.webhook_events.repository_id is '仓库 ID，可为空 / Repository ID, nullable';
comment on column public.webhook_events.provider is '代码托管平台 / Git provider';
comment on column public.webhook_events.event_type is '事件类型 / Event type';
comment on column public.webhook_events.delivery_id is '平台投递 ID / Provider delivery ID';
comment on column public.webhook_events.signature_valid is '验签是否成功 / Whether signature validation passed';
comment on column public.webhook_events.payload_hash is '请求体哈希 / Payload hash';
comment on column public.webhook_events.status is '处理状态 / Processing status';
comment on column public.webhook_events.payload is '原始事件载荷 JSON / Raw webhook payload JSON';
comment on column public.webhook_events.processed_at is '处理完成时间 / Processed at';
comment on column public.webhook_events.error_message is '错误信息 / Error message';
comment on column public.webhook_events.created_at is '创建时间 / Created at';
comment on column public.webhook_events.updated_at is '更新时间 / Updated at';

comment on table public.pull_requests is '拉取请求主表 / Pull requests';
comment on column public.pull_requests.id is '主键 ID / Primary key ID';
comment on column public.pull_requests.organization_id is '所属组织 ID / Organization ID';
comment on column public.pull_requests.repository_id is '仓库 ID / Repository ID';
comment on column public.pull_requests.provider_pr_id is '平台侧 PR ID / Provider pull request ID';
comment on column public.pull_requests.provider_pr_number is '平台侧 PR 编号 / Provider pull request number';
comment on column public.pull_requests.title is 'PR 标题 / Pull request title';
comment on column public.pull_requests.description is 'PR 描述 / Pull request description';
comment on column public.pull_requests.author_login is '作者登录名 / Author login';
comment on column public.pull_requests.base_branch is '目标分支 / Base branch';
comment on column public.pull_requests.head_branch is '来源分支 / Head branch';
comment on column public.pull_requests.base_sha is '当前基准提交 SHA / Current base SHA';
comment on column public.pull_requests.head_sha is '当前头提交 SHA / Current head SHA';
comment on column public.pull_requests.state is 'PR 状态 / Pull request state';
comment on column public.pull_requests.opened_at is '打开时间 / Opened at';
comment on column public.pull_requests.closed_at is '关闭时间 / Closed at';
comment on column public.pull_requests.merged_at is '合并时间 / Merged at';
comment on column public.pull_requests.latest_review_run_id is '最近一次审查运行 ID / Latest review run ID';
comment on column public.pull_requests.created_at is '创建时间 / Created at';
comment on column public.pull_requests.updated_at is '更新时间 / Updated at';

comment on table public.pr_commits is 'PR 提交记录表 / Pull request commits';
comment on column public.pr_commits.id is '主键 ID / Primary key ID';
comment on column public.pr_commits.organization_id is '所属组织 ID / Organization ID';
comment on column public.pr_commits.pull_request_id is 'PR ID / Pull request ID';
comment on column public.pr_commits.commit_sha is '提交 SHA / Commit SHA';
comment on column public.pr_commits.parent_sha is '父提交 SHA / Parent commit SHA';
comment on column public.pr_commits.author_name is '作者姓名 / Author name';
comment on column public.pr_commits.author_email is '作者邮箱 / Author email';
comment on column public.pr_commits.committed_at is '提交时间 / Committed at';
comment on column public.pr_commits.created_at is '创建时间 / Created at';
comment on column public.pr_commits.updated_at is '更新时间 / Updated at';

comment on table public.rule_sets is '规则集主表 / Rule sets';
comment on column public.rule_sets.id is '主键 ID / Primary key ID';
comment on column public.rule_sets.organization_id is '所属组织 ID / Organization ID';
comment on column public.rule_sets.repository_id is '仓库 ID / Repository ID';
comment on column public.rule_sets.source_type is '规则来源类型 / Rule source type';
comment on column public.rule_sets.name is '规则集名称 / Rule set name';
comment on column public.rule_sets.is_active is '是否启用 / Whether the rule set is active';
comment on column public.rule_sets.current_version_id is '当前生效版本 ID / Current active version ID';
comment on column public.rule_sets.last_applied_at is '最近生效时间 / Last applied at';
comment on column public.rule_sets.created_at is '创建时间 / Created at';
comment on column public.rule_sets.updated_at is '更新时间 / Updated at';

comment on table public.rule_versions is '规则版本表 / Rule versions';
comment on column public.rule_versions.id is '主键 ID / Primary key ID';
comment on column public.rule_versions.organization_id is '所属组织 ID / Organization ID';
comment on column public.rule_versions.rule_set_id is '规则集 ID / Rule set ID';
comment on column public.rule_versions.version_no is '版本号 / Version number';
comment on column public.rule_versions.content_yaml is 'YAML 原文 / Raw YAML content';
comment on column public.rule_versions.content_json is '解析后的 JSON 内容 / Parsed JSON content';
comment on column public.rule_versions.checksum is '内容校验哈希 / Content checksum';
comment on column public.rule_versions.validation_status is '校验状态 / Validation status';
comment on column public.rule_versions.validation_errors is '校验错误 JSON / Validation errors JSON';
comment on column public.rule_versions.source_commit_sha is '来源提交 SHA / Source commit SHA';
comment on column public.rule_versions.created_by_user_id is '创建人用户 ID，对应 app_users.id / Creator user ID referencing app_users.id';
comment on column public.rule_versions.created_at is '创建时间 / Created at';
comment on column public.rule_versions.updated_at is '更新时间 / Updated at';

comment on table public.ai_provider_configs is '模型提供商配置表 / AI provider configurations';
comment on column public.ai_provider_configs.id is '主键 ID / Primary key ID';
comment on column public.ai_provider_configs.organization_id is '所属组织 ID / Organization ID';
comment on column public.ai_provider_configs.provider is '模型提供商 / AI provider';
comment on column public.ai_provider_configs.display_name is '展示名称 / Display name';
comment on column public.ai_provider_configs.vault_secret_id is 'Vault 密钥 ID / Vault secret ID';
comment on column public.ai_provider_configs.base_url is '自定义接口基地址 / Custom base URL';
comment on column public.ai_provider_configs.masked_key_suffix is '掩码密钥后缀 / Masked key suffix';
comment on column public.ai_provider_configs.is_active is '是否启用 / Whether the provider config is active';
comment on column public.ai_provider_configs.created_by_user_id is '创建人用户 ID，对应 app_users.id / Creator user ID referencing app_users.id';
comment on column public.ai_provider_configs.metadata is '扩展配置 JSON / Extended config metadata JSON';
comment on column public.ai_provider_configs.created_at is '创建时间 / Created at';
comment on column public.ai_provider_configs.updated_at is '更新时间 / Updated at';

comment on table public.ai_provider_bindings is '模型绑定表 / AI provider bindings';
comment on column public.ai_provider_bindings.id is '主键 ID / Primary key ID';
comment on column public.ai_provider_bindings.organization_id is '所属组织 ID / Organization ID';
comment on column public.ai_provider_bindings.repository_id is '仓库 ID，空表示组织级默认 / Repository ID, null means organization-level default';
comment on column public.ai_provider_bindings.task_type is 'AI 任务类型 / AI task type';
comment on column public.ai_provider_bindings.provider_config_id is '主模型配置 ID / Primary provider config ID';
comment on column public.ai_provider_bindings.model_name is '主模型名称 / Primary model name';
comment on column public.ai_provider_bindings.fallback_provider_config_id is '回退模型配置 ID / Fallback provider config ID';
comment on column public.ai_provider_bindings.fallback_model_name is '回退模型名称 / Fallback model name';
comment on column public.ai_provider_bindings.is_active is '是否启用 / Whether the binding is active';
comment on column public.ai_provider_bindings.priority is '优先级 / Priority';
comment on column public.ai_provider_bindings.created_at is '创建时间 / Created at';
comment on column public.ai_provider_bindings.updated_at is '更新时间 / Updated at';

comment on table public.review_runs is '审查运行表 / Review runs';
comment on column public.review_runs.id is '主键 ID / Primary key ID';
comment on column public.review_runs.organization_id is '所属组织 ID / Organization ID';
comment on column public.review_runs.repository_id is '仓库 ID / Repository ID';
comment on column public.review_runs.pull_request_id is 'PR ID / Pull request ID';
comment on column public.review_runs.run_number is 'PR 内部递增运行号 / Incremental run number within a PR';
comment on column public.review_runs.trigger_type is '触发来源 / Trigger type';
comment on column public.review_runs.trigger_event_id is '对应的 webhook 事件 ID / Related webhook event ID';
comment on column public.review_runs.review_mode is '审查模式 / Review mode';
comment on column public.review_runs.output_language is '输出语言 / Output language';
comment on column public.review_runs.status is '运行状态 / Review run status';
comment on column public.review_runs.base_sha is '本次审查基准 SHA / Base SHA for this run';
comment on column public.review_runs.head_sha is '本次审查头部 SHA / Head SHA for this run';
comment on column public.review_runs.queue_job_id is '队列任务 ID / Queue job ID';
comment on column public.review_runs.ai_provider_config_id is '主模型配置 ID / Primary AI provider config ID';
comment on column public.review_runs.ai_model_name is '主模型名称 / Primary AI model name';
comment on column public.review_runs.fallback_provider_config_id is '回退模型配置 ID / Fallback AI provider config ID';
comment on column public.review_runs.fallback_model_name is '回退模型名称 / Fallback AI model name';
comment on column public.review_runs.rule_snapshot is '本次生效规则快照 JSON / Effective rule snapshot JSON';
comment on column public.review_runs.summary_md is 'PR 摘要 Markdown / PR summary in Markdown';
comment on column public.review_runs.analyzed_files_count is '分析文件数 / Number of analyzed files';
comment on column public.review_runs.findings_count is '问题总数 / Total findings count';
comment on column public.review_runs.security_findings_count is '安全问题数 / Security findings count';
comment on column public.review_runs.started_at is '开始时间 / Started at';
comment on column public.review_runs.finished_at is '结束时间 / Finished at';
comment on column public.review_runs.error_code is '错误码 / Error code';
comment on column public.review_runs.error_message is '错误信息 / Error message';
comment on column public.review_runs.created_at is '创建时间 / Created at';
comment on column public.review_runs.updated_at is '更新时间 / Updated at';

comment on table public.changed_files is '变更文件快照表 / Changed files snapshots';
comment on column public.changed_files.id is '主键 ID / Primary key ID';
comment on column public.changed_files.organization_id is '所属组织 ID / Organization ID';
comment on column public.changed_files.pull_request_id is 'PR ID / Pull request ID';
comment on column public.changed_files.review_run_id is '审查运行 ID / Review run ID';
comment on column public.changed_files.file_path is '当前文件路径 / Current file path';
comment on column public.changed_files.previous_path is '重命名前路径 / Previous file path before rename';
comment on column public.changed_files.change_type is '变更类型 / Change type';
comment on column public.changed_files.additions is '新增行数 / Number of added lines';
comment on column public.changed_files.deletions is '删除行数 / Number of deleted lines';
comment on column public.changed_files.is_binary is '是否二进制文件 / Whether the file is binary';
comment on column public.changed_files.patch_excerpt is 'Diff 摘要片段 / Diff patch excerpt';
comment on column public.changed_files.created_at is '创建时间 / Created at';
comment on column public.changed_files.updated_at is '更新时间 / Updated at';

comment on table public.review_issues is '审查问题表 / Review issues';
comment on column public.review_issues.id is '主键 ID / Primary key ID';
comment on column public.review_issues.organization_id is '所属组织 ID / Organization ID';
comment on column public.review_issues.repository_id is '仓库 ID / Repository ID';
comment on column public.review_issues.pull_request_id is 'PR ID / Pull request ID';
comment on column public.review_issues.review_run_id is '审查运行 ID / Review run ID';
comment on column public.review_issues.fingerprint is '问题指纹，用于去重 / Issue fingerprint for deduplication';
comment on column public.review_issues.issue_type is '问题类型 / Issue type';
comment on column public.review_issues.category is '问题分类 / Issue category';
comment on column public.review_issues.title is '问题标题 / Issue title';
comment on column public.review_issues.summary is '问题摘要 / Issue summary';
comment on column public.review_issues.severity is '严重级别 / Severity';
comment on column public.review_issues.confidence_score is '置信度评分 / Confidence score';
comment on column public.review_issues.fixability_score is '可修复度评分 / Fixability score';
comment on column public.review_issues.file_path is '关联文件路径 / Related file path';
comment on column public.review_issues.start_line is '起始行 / Start line';
comment on column public.review_issues.end_line is '结束行 / End line';
comment on column public.review_issues.code_excerpt is '代码片段 / Code excerpt';
comment on column public.review_issues.suggestion_md is '修复建议 Markdown / Suggestion in Markdown';
comment on column public.review_issues.root_cause is '根因分析 / Root cause';
comment on column public.review_issues.impact_scope is '影响范围 / Impact scope';
comment on column public.review_issues.status is '问题状态 / Issue status';
comment on column public.review_issues.first_seen_run_id is '首次出现的运行 ID / First seen review run ID';
comment on column public.review_issues.last_seen_run_id is '最近出现的运行 ID / Last seen review run ID';
comment on column public.review_issues.resolved_in_run_id is '被解决的运行 ID / Resolved in review run ID';
comment on column public.review_issues.ignored_by_user_id is '忽略人用户 ID，对应 app_users.id / Ignored by user ID referencing app_users.id';
comment on column public.review_issues.ignored_reason is '忽略原因 / Ignored reason';
comment on column public.review_issues.created_at is '创建时间 / Created at';
comment on column public.review_issues.updated_at is '更新时间 / Updated at';

comment on table public.review_comments is '审查评论表 / Review comments';
comment on column public.review_comments.id is '主键 ID / Primary key ID';
comment on column public.review_comments.organization_id is '所属组织 ID / Organization ID';
comment on column public.review_comments.pull_request_id is 'PR ID / Pull request ID';
comment on column public.review_comments.review_run_id is '审查运行 ID / Review run ID';
comment on column public.review_comments.review_issue_id is '审查问题 ID / Review issue ID';
comment on column public.review_comments.provider is '代码托管平台 / Git provider';
comment on column public.review_comments.external_comment_id is '平台侧评论 ID / Provider comment ID';
comment on column public.review_comments.body_md is '评论正文 Markdown / Comment body in Markdown';
comment on column public.review_comments.output_language is '输出语言 / Output language';
comment on column public.review_comments.status is '评论状态 / Comment status';
comment on column public.review_comments.is_inline is '是否行内评论 / Whether the comment is inline';
comment on column public.review_comments.file_path is '评论文件路径 / Comment file path';
comment on column public.review_comments.line_number is '评论行号 / Comment line number';
comment on column public.review_comments.posted_at is '发布时间 / Posted at';
comment on column public.review_comments.last_synced_at is '最近同步时间 / Last synced at';
comment on column public.review_comments.error_message is '发布错误信息 / Posting error message';
comment on column public.review_comments.created_at is '创建时间 / Created at';
comment on column public.review_comments.updated_at is '更新时间 / Updated at';

comment on table public.review_feedback is '审查反馈表 / Review feedback';
comment on column public.review_feedback.id is '主键 ID / Primary key ID';
comment on column public.review_feedback.organization_id is '所属组织 ID / Organization ID';
comment on column public.review_feedback.review_issue_id is '审查问题 ID / Review issue ID';
comment on column public.review_feedback.review_run_id is '审查运行 ID / Review run ID';
comment on column public.review_feedback.user_id is '反馈用户 ID，对应 app_users.id / Feedback user ID referencing app_users.id';
comment on column public.review_feedback.feedback_type is '反馈类型 / Feedback type';
comment on column public.review_feedback.reason is '反馈原因 / Feedback reason';
comment on column public.review_feedback.created_at is '创建时间 / Created at';
comment on column public.review_feedback.updated_at is '更新时间 / Updated at';

comment on table public.agent_prompts is 'Agent 修复提示词表 / Agent prompts';
comment on column public.agent_prompts.id is '主键 ID / Primary key ID';
comment on column public.agent_prompts.organization_id is '所属组织 ID / Organization ID';
comment on column public.agent_prompts.repository_id is '仓库 ID / Repository ID';
comment on column public.agent_prompts.pull_request_id is 'PR ID / Pull request ID';
comment on column public.agent_prompts.review_run_id is '审查运行 ID / Review run ID';
comment on column public.agent_prompts.source_type is '来源类型，如单问题或多问题 / Source type such as single issue or multi issue';
comment on column public.agent_prompts.source_issue_ids is '来源问题 ID 数组 / Source issue ID array';
comment on column public.agent_prompts.agent_kind is 'Agent 类型 / Agent kind';
comment on column public.agent_prompts.output_language is '输出语言 / Output language';
comment on column public.agent_prompts.prompt_md is '提示词正文 Markdown / Prompt body in Markdown';
comment on column public.agent_prompts.prompt_hash is '提示词内容哈希 / Prompt content hash';
comment on column public.agent_prompts.generated_by_user_id is '生成人用户 ID，对应 app_users.id / Generated by user ID referencing app_users.id';
comment on column public.agent_prompts.copied_count is '复制次数 / Copy count';
comment on column public.agent_prompts.last_copied_at is '最近复制时间 / Last copied at';
comment on column public.agent_prompts.created_at is '创建时间 / Created at';
comment on column public.agent_prompts.updated_at is '更新时间 / Updated at';

comment on table public.usage_events is '使用与计量事件表 / Usage events';
comment on column public.usage_events.id is '主键 ID / Primary key ID';
comment on column public.usage_events.organization_id is '所属组织 ID / Organization ID';
comment on column public.usage_events.repository_id is '仓库 ID / Repository ID';
comment on column public.usage_events.pull_request_id is 'PR ID / Pull request ID';
comment on column public.usage_events.review_run_id is '审查运行 ID / Review run ID';
comment on column public.usage_events.review_issue_id is '审查问题 ID / Review issue ID';
comment on column public.usage_events.agent_prompt_id is 'Agent 提示词 ID / Agent prompt ID';
comment on column public.usage_events.event_type is '事件类型 / Event type';
comment on column public.usage_events.task_type is 'AI 任务类型 / AI task type';
comment on column public.usage_events.provider_config_id is '模型配置 ID / AI provider config ID';
comment on column public.usage_events.provider is '模型提供商 / AI provider';
comment on column public.usage_events.model_name is '模型名称 / Model name';
comment on column public.usage_events.input_tokens is '输入 Token 数 / Input token count';
comment on column public.usage_events.output_tokens is '输出 Token 数 / Output token count';
comment on column public.usage_events.latency_ms is '调用耗时毫秒 / Latency in milliseconds';
comment on column public.usage_events.estimated_cost is '预估成本 / Estimated cost';
comment on column public.usage_events.success is '是否成功 / Whether the event succeeded';
comment on column public.usage_events.error_code is '错误码 / Error code';
comment on column public.usage_events.metadata is '扩展信息 JSON / Extended metadata JSON';
comment on column public.usage_events.occurred_at is '事件发生时间 / Occurred at';
comment on column public.usage_events.created_at is '创建时间 / Created at';
comment on column public.usage_events.updated_at is '更新时间 / Updated at';
